
# purpose - identify baskets of stocks want to analyze 

mary_jane <- c('FB',
             'ARNA',
             'IAN',
             'CARA',
             'GWPH',
             'HEXO',
             'OGI',
             'TGOD',
             'ACRG',
             'WEED',
             'ACB',
             'CURA',
             'KSHB',
             'NWKRF',
             'GTII',
             'IIPR',
             'HARV',
             'CRON',
             'TLRY',
             'LABS',
             'SMG',
             'CRBP',
             'CVSI',
             'APHA',
             'CWEB',
             'VFF')

restaurant <- c('EAT',
                'DRI',
                'DIN',
                'MCD',
                'QSR',
                'SBUX',
                'YUM',
                'YUMC')

real_estate <- c('KRG',
                 'OHI',
                 'SNH',
                 'STAG',
                 'VER')

oil_gas <- c('EQM', 
             'BP',
             'RDS-A',
             'EQNR',
             'TOT',
             'XOM',
             'E',
             'CVX',
             'PTR',
             'COP',
             'ENI',
             'OXY',
             'SU',
             'CNQ')

tech <- c('FB',
          'MSFT',
          'GOOGL',
          'BABA',
          'IBM',
          'AMZN',
          'DOCU',
          'WORK',
          'TCEHY')
